FROM nginx:alpine 
# Usa a imagem do nginx baseada no Alpine Linux
COPY index.html /usr/share/nginx/html/index.html 
# Copia o arquivo index.html para o diretório do nginx
EXPOSE 80 
# Porta da interação de dentro